<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>StudentPortal.EnrollmentService.GrpcService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.1.0" />
      <PackageReference Include="Grpc.Core" Version="2.46.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-rc.2.25502.107" />
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\StudentPortal.Enrollment.BLL\StudentPortal.Enrollment.BLL.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\enrollment.proto" GrpcServices="Server" />
    </ItemGroup>
</Project>
