<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.StackExchange.Redis" Version="9.5.2" />
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
      <PackageReference Include="FluentValidation" Version="9.5.4" />
      <PackageReference Include="Google.Protobuf" Version="3.33.0" />
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
      <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
      <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0-rc.2.25502.107" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    </ItemGroup>

</Project>
