<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>081acf5e-0b02-49fc-a86b-d82d075c74c1</UserSecretsId>
        <RootNamespace>StudentPortal.Enrollment.AppHost</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting" Version="9.5.0" />
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0"/>
        <PackageReference Include="Aspire.Hosting.MongoDB" Version="9.4.2" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.0" />
        <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.5.0" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.0" />
        <PackageReference Include="Aspire.StackExchange.Redis" Version="9.5.2" />
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
        <PackageReference Include="FluentValidation" Version="9.5.4" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="9.5.4" />
        <PackageReference Include="Google.Protobuf" Version="3.33.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
        <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
        <PackageReference Include="Grpc.Tools" Version="2.76.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0-rc.2.25502.107" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
        <PackageReference Include="MongoDB.Bson" Version="3.5.0" />
        <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
        <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DiscussionService\StudentPortal.DiscussionService.Application\StudentPortal.DiscussionService.Application.csproj" />
      <ProjectReference Include="..\StudentPortal.AggregatorService\StudentPortal.AggregatorService.csproj" />
      <ProjectReference Include="..\StudentPortal.ApiGateway\StudentPortal.ApiGateway.csproj" />
      <ProjectReference Include="..\StudentPortal.CourseCatalogService.Apii\StudentPortal.CourseCatalogService.Apii.csproj" />
      <ProjectReference Include="..\StudentPortal.CourseCatalogService.BLL\StudentPortal.CourseCatalogService.BLL.csproj" />
      <ProjectReference Include="..\StudentPortal.CourseCatalogService.DAL\StudentPortal.CourseCatalogService.DAL.csproj" />
      <ProjectReference Include="..\StudentPortal.DiscussionService.Api\StudentPortal.DiscussionService.Api.csproj" />
      <ProjectReference Include="..\StudentPortal.DiscussionService.Infrastructure\StudentPortal.DiscussionService.Infrastructure.csproj" />
      <ProjectReference Include="..\StudentPortal.Enrollment.Api\StudentPortal.Enrollment.Api.csproj" />
      <ProjectReference Include="..\StudentPortal.Enrollment.BLL\StudentPortal.Enrollment.BLL.csproj" />
      <ProjectReference Include="..\StudentPortal.Enrollment.DAL\StudentPortal.Enrollment.DAL.csproj" />
      <ProjectReference Include="..\StudentPortal.Enrollment.Domain\StudentPortal.Enrollment.Domain.csproj" />
    </ItemGroup>



</Project>
